### ISSUE TITLE
ติดปัญหา module OCA thai ล่าสุด ไม่สามารถลงได้ ใน version 13

### ISSUE THREAD

**Issue by nine-m** [poonlap/odoo-th#3]
มี 2 module ลงไม่ได้คือ Thailand Localization - TAX Reports และ Thailand Localization - Withholding Tax Report 

ติด dependencies  คือ date_range และ report_xlsx 

ต้องแก้ไขยังไงครับ เท่าที่ดูเหมือน OCA thai ทำ module ไม่เหมือนใน readme

**Comment by poonlap** [comment]
ผมไม่ได้อัพเดทนานแล้วครับ พอดี l10n-thailand มีโมดูลเพิ่มขึ้นมาซึ่งต้องการ 
https://github.com/OCA/reporting-engine/tree/13.0 กับ https://github.com/OCA/server-ux/tree/13.0
ตอนนี้เพิ่มเข้าไปแล้วครับ ([Dockerfile](https://github.com/poonlap/odoo-th/blob/master/Dockerfile))
ลองใช้ดูนะครับ 

ขอบคุณนะครับที่ช่วยแจ้งให้ทราบ

![image](https://user-images.githubusercontent.com/16228313/92365482-190fcc00-f11e-11ea-9546-69918e5054cb.png)
