### ISSUE TITLE
หา Geo ไม่เจอครับ

### ISSUE THREAD

**Issue by songwutk** [poonlap/odoo-th#4]
![Screenshot from 2020-09-14 15-00-11](https://user-images.githubusercontent.com/2949361/93059745-60a4d380-f69b-11ea-8e9c-b0672d4081cc.png)

**Comment by poonlap** [comment]
ขอ parameter ตอนรัน docker หน่อยครับ ว่าเป็นอย่างไรครับ.
อันนี้จากเครื่องผมครับ

![image](https://user-images.githubusercontent.com/16228313/93065280-b630ae80-f6a2-11ea-89bf-6302ac214be0.png)

**Comment by songwutk** [comment]
version: '2'
services:
  odoo14:
    container_name: odoo    
    image: poonlap/odoo-th:latest
    ports:
      - "8069:8069"
    tty: true
    command: -- --dev=reload
#    command: odoo scaffold /mnt/extra-addons/test_module
    volumes:
      - ./addons:/mnt/extra-addons
      - ./etc/odoo:/etc/odoo
      - ./log:/var/log/odoo      
      - ./filestore:/var/lib/odoo/filestore
    restart: always             # run as a service

**Comment by songwutk** [comment]
ย่อหน้าอาจจะเพี้ยนหน่อยนะครับ 

`version: '2'
services:
  odoo14:
    container_name: odoo    
    image: poonlap/odoo-th:latest
    ports:
      - "8069:8069"
    tty: true
    command: -- --dev=reload
 
    volumes:
      - ./addons:/mnt/extra-addons
      - ./etc/odoo:/etc/odoo
      - ./log:/var/log/odoo      
      - ./filestore:/var/lib/odoo/filestore
    restart: always             # run as a service
`

**Comment by poonlap** [comment]
ใน odoo.conf มี partner-contact ไหมครับ

`addons_path = /mnt/extra-addons, /opt/odoo/addons/l10n-thailand, /opt/odoo/addons/web, /mnt/extra-addons/14.0, /opt/odoo/addons/partner-contact, /opt/odoo/addons/server-ux, /opt/odoo/addons/reporting-engine`

**Comment by songwutk** [comment]
ผมคงขาดตรงนี้ไป ขอบคุณครับอาจารย์

**Comment by poonlap** [comment]
ไม่เป็นไรครับ  ขอบคุณครับที่ช่วยใช้และรายงานครับ
v14 มันจะใช้ base_location ของ v13 ไม่ผ่านนะครับ จะติดตอน install เหมือนกับ parse xml ไม่ผ่าน 
ลองใช้ base_location จากที่นี่ดูนะครับ ผมลองแก้ให้ใช้ได้แบบผ่านๆไปก่อน ไม่เช่นนั้นจะใช้ l10n_th_base_location ไม่ได้ครับ
https://github.com/poonlap/odoo-th/tree/master/example/addons/14.0
